name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: check eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: components/**/*.{ts,tsx} lib/**/*.{ts,tsx} pages/**/*.{ts,tsx}
