name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: check eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: components/**/*.{ts,tsx} lib/**/*.{ts,tsx} pages/**/*.{ts,tsx}
